### ISSUE TITLE
很棒 我已经用上了 但是还有个小问题 

### ISSUE THREAD

**Issue by born198x** [TriDiamond/hexo-theme-obsidian#17]
老司机，能否将文档写的更详细点呢？我的博客 http://blog.vxiangwang.com 怎么刷成你最新的样式呢？

**Comment by TriDiamond** [comment]
## 更新主题

> 更新前请先备份主题里的 `_config.yml` 文件

``` bash
cd themes/osidian
git pull
```

我后面会重写一个主题配置文档。谢谢你的支持。

**Comment by born198x** [comment]
刚更新了你的主题，也用上了，目前有一个问题：我启用的是 valine 评论统计插件，目测挂了，https://avoscloud.com/1.1/classes/Counter 依赖这个统计中心吗？麻烦确认下哈 。另外about这个页面有处理么？

![image](https://user-images.githubusercontent.com/57509061/68536071-c774a480-0387-11ea-8c55-5f243c4e68bd.png)

**Comment by born198x** [comment]
还有个感觉也是 valine 插件问题，能否一起看下？进文章详情，发现阅读次数直接是100万了...

![image](https://user-images.githubusercontent.com/57509061/68536093-4ff34500-0388-11ea-9265-e8864a787d26.png)

**Comment by TriDiamond** [comment]
@born198x 我这里用的直接是valine评论自带的统计哈，不是counter里面的。

**Comment by born198x** [comment]
目测是自动请求那个 counter地址的 我也没改啥呢  要么大佬研究下？

**Comment by TriDiamond** [comment]
@born198x 你的配置发一下给我看看。

**Comment by born198x** [comment]
hi ，我发现我文章里的 代码块样式没效果，你那边有处理么？看图

![image](https://user-images.githubusercontent.com/57509061/69015127-00d29300-09cc-11ea-83d0-55a68016c3e9.png)

**Comment by Fenco-Han** [comment]
修改代码格式发自我的iPhone------------------ 原始邮件 ------------------发件人: born198x  <notifications@github.com>发送时间: 2019年11月18日 06:24收件人: TriDiamond/hexo-theme-obsidian <hexo-theme-obsidian@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[TriDiamond/hexo-theme-obsidian] 很棒 我已经用上了 但是还有个小问题  (#17)hi ，我发现我文章里的 代码块样式没效果，你那边有处理么？看图


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/TriDiamond/hexo-theme-obsidian/issues/17?email_source=notifications\u0026email_token=AMTBZPLNBKI5XCSUZCQO6BDQUHAAJA5CNFSM4JKPSXDKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEIX2MY#issuecomment-554794291",
"url": "https://github.com/TriDiamond/hexo-theme-obsidian/issues/17?email_source=notifications\u0026email_token=AMTBZPLNBKI5XCSUZCQO6BDQUHAAJA5CNFSM4JKPSXDKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEIX2MY#issuecomment-554794291",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by born198x** [comment]
> 改代码格式发自我的iPhone

看不清楚 能直接电脑操作下么？

**Comment by TriDiamond** [comment]
@born198x 代码块的写法是这个符号，符号用错了

```markdown

    ```
    port 700
    ```

```

**Comment by born198x** [comment]
> @born198x 代码块的写法是这个符号，符号用错了
> 
> ```gfm
>     ```
>     port 700
>     ```
> ```

这种符号 我也用了 一样的 都不行

**Comment by TriDiamond** [comment]
代码块前后留空行。估计是语法有错误。打包的时候有报错吗？试试 `hexo clean && hexo g && hexo server`

**Comment by born198x** [comment]
> 代码块前后留空行。估计是语法有错误。打包的时候有报错吗？试试 `hexo clean && hexo g && hexo server`

打包的时候没有任何报错，所以我也很奇怪 以为主题影响了默认Markdown语法呢...

**Comment by born198x** [comment]
我先关了这个 issue吧，具体的细节 我再研究研究，有结果再分享吧
